# Description:
# OMR pipelines and Apache Beam utilities.
package(
    default_visibility = ["//moonlight:__subpackages__"],
)

licenses(["notice"])  # Apache 2.0

py_library(
    name = "pipeline_flags",
    srcs = ["pipeline_flags.py"],
    deps = [
        # absl dep
        # apache-beam dep
    ],
    srcs_version = "PY2ONLY",
)
