# Description:
# Common logic for all model training.

package(
    default_visibility = ["//moonlight:__subpackages__"],
)

licenses(["notice"])  # Apache 2.0

py_library(
    name = "glyph_patches",
    srcs = ["glyph_patches.py"],
    srcs_version = "PY2AND3",
    deps = [
        # absl dep
        "//moonlight/protobuf:protobuf_py_pb2",
        # tensorflow dep
    ],
)
